
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    entrypoint: ["/app/scripts/deploy.sh", "&&", "air"]
    container_name: crud_app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: crud_db

  adminer_backend:
    image: michalhosna/adminer
    ports:
      - "8094:8080"
    depends_on:
      - db
    environment:
      ADMINER_DB: "${DB_DATABASE:-app}"
      ADMINER_PASSWORD: "${DB_PASSWORD:-secret}"
      ADMINER_SERVER: "${DB_HOST:-mysql}"
      ADMINER_USERNAME: "${DB_USERNAME:-app}"
      ADMINER_AUTOLOGIN: 1
    container_name: crud_adm
volumes:
  postgres_data:
